env:
  DIRECTORY: dist
  PROJECT_NAME: refined-prun

name: Release
on:
  workflow_dispatch: null
jobs:

  build:
    name: Build
    outputs:
      created: ${{ env.DAILY_VERSION_CREATED }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Create tag if necessary
        uses: fregante/daily-version-action@v2
      - name: Update manifest.json with version ${{ env.DAILY_VERSION }}
        if: env.DAILY_VERSION_CREATED
        run: npx dot-json@1 "$DIRECTORY/manifest.json" version "$DAILY_VERSION"
      - name: Ready for "submit" jobs
        if: env.DAILY_VERSION_CREATED
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.DIRECTORY }}
      - name: Create release
        if: env.DAILY_VERSION_CREATED
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ env.DIRECTORY }}
        run: |
          FILENAME="$PROJECT_NAME-$DAILY_VERSION-for-local-testing-only.zip"
          zip -r "$FILENAME" ./*
          # Create as draft to curate it before sending it out
          gh release create "$DAILY_VERSION" "$FILENAME" --notes "For the changelog, please refer to https://github.com/refined-prun/refined-prun/blob/main/CHANGELOG.md for details."

  chrome:
    if: needs.build.outputs.created
    needs: build
    name: Submit (Chrome)
    environment: Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: actions/download-artifact@v4
      - run: npx chrome-webstore-upload-cli@3
        working-directory: artifact
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  firefox:
    if: needs.build.outputs.created
    needs: build
    name: Submit (Firefox)
    environment: Firefox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Zip source code
        run: git archive --output source.zip HEAD

      - uses: actions/download-artifact@v4
      - name: Upload build and source code
        run: npx web-ext@8 sign --channel listed --upload-source-code ../source.zip
        working-directory: artifact
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
